name: swifty_companion
description: A new Flutter project for the 42 Swifty Companion.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Networking & API
  dio: ^5.3.0
  pretty_dio_logger: ^1.3.1

  # State Management
  provider: ^6.0.5

  # Environment Variables
  flutter_dotenv: ^5.1.0

  # Service Locator (Singletons)
  get_it: ^7.6.0

  # Secure Storage (For keeping the token safe)
  flutter_secure_storage: ^9.0.0

  # UI Utilities
  cached_network_image: ^3.3.0
  flutter_svg: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
  - .env